# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [9]:
pip install geoviews

Collecting geoviews
  Downloading geoviews-1.14.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: bokeh>=3.6.0 in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (3.6.0)
Collecting cartopy>=0.18.0 (from geoviews)
  Downloading Cartopy-0.24.1-cp312-cp312-win_amd64.whl.metadata (8.1 kB)
Requirement already satisfied: holoviews>=1.16.0 in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (1.20.2)
Requirement already satisfied: numpy in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (1.26.4)
Requirement already satisfied: packaging in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (24.1)
Requirement already satisfied: panel>=1.0.0 in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (1.5.2)
Requirement already satisfied: param<3.0,>=1.9.3 in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (2.1.1)
Collecting pyproj (from geoviews)
  Downloading pyproj-3.7.1-cp312-cp312-win_amd64.whl.metadata (31 kB)
Collecting shapely (from geoviews)
  Downloading shapely-2.1.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: xyzservices in c:\users\44779\anaconda3\lib\site-packages (from geoviews) (2022.9.0)
Requirement already satisfied: Jinja2>=2.9 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (3.1.4)
Requirement already satisfied: contourpy>=1.2 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (1.2.0)
Requirement already satisfied: pandas>=1.2 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (2.2.2)
Requirement already satisfied: pillow>=7.1.0 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (10.4.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (6.0.1)
Requirement already satisfied: tornado>=6.2 in c:\users\44779\anaconda3\lib\site-packages (from bokeh>=3.6.0->geoviews) (6.4.1)
Requirement already satisfied: matplotlib>=3.6 in c:\users\44779\anaconda3\lib\site-packages (from cartopy>=0.18.0->geoviews) (3.9.1)
Collecting pyshp>=2.3 (from cartopy>=0.18.0->geoviews)
  Downloading pyshp-2.3.1-py2.py3-none-any.whl.metadata (55 kB)
Requirement already satisfied: colorcet in c:\users\44779\anaconda3\lib\site-packages (from holoviews>=1.16.0->geoviews) (3.1.0)
Requirement already satisfied: pyviz-comms>=2.1 in c:\users\44779\anaconda3\lib\site-packages (from holoviews>=1.16.0->geoviews) (3.0.2)
Requirement already satisfied: bleach in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (4.1.0)
Requirement already satisfied: linkify-it-py in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (2.0.0)
Requirement already satisfied: markdown in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (3.4.1)
Requirement already satisfied: markdown-it-py in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (0.3.0)
Requirement already satisfied: requests in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (2.32.3)
Requirement already satisfied: tqdm in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (4.66.5)
Requirement already satisfied: typing-extensions in c:\users\44779\anaconda3\lib\site-packages (from panel>=1.0.0->geoviews) (4.13.2)
Requirement already satisfied: certifi in c:\users\44779\anaconda3\lib\site-packages (from pyproj->geoviews) (2025.4.26)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\44779\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh>=3.6.0->geoviews) (2.1.3)
Requirement already satisfied: cycler>=0.10 in c:\users\44779\anaconda3\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\44779\anaconda3\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\44779\anaconda3\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\44779\anaconda3\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\44779\anaconda3\lib\site-packages (from matplotlib>=3.6->cartopy>=0.18.0->geoviews) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\44779\anaconda3\lib\site-packages (from pandas>=1.2->bokeh>=3.6.0->geoviews) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\44779\anaconda3\lib\site-packages (from pandas>=1.2->bokeh>=3.6.0->geoviews) (2023.3)
Requirement already satisfied: six>=1.9.0 in c:\users\44779\anaconda3\lib\site-packages (from bleach->panel>=1.0.0->geoviews) (1.16.0)
Requirement already satisfied: webencodings in c:\users\44779\anaconda3\lib\site-packages (from bleach->panel>=1.0.0->geoviews) (0.5.1)
Requirement already satisfied: uc-micro-py in c:\users\44779\anaconda3\lib\site-packages (from linkify-it-py->panel>=1.0.0->geoviews) (1.0.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\44779\anaconda3\lib\site-packages (from markdown-it-py->panel>=1.0.0->geoviews) (0.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\44779\anaconda3\lib\site-packages (from requests->panel>=1.0.0->geoviews) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\44779\anaconda3\lib\site-packages (from requests->panel>=1.0.0->geoviews) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\44779\anaconda3\lib\site-packages (from requests->panel>=1.0.0->geoviews) (2.4.0)
Requirement already satisfied: colorama in c:\users\44779\anaconda3\lib\site-packages (from tqdm->panel>=1.0.0->geoviews) (0.4.6)
Downloading geoviews-1.14.0-py3-none-any.whl (547 kB)
   ---------------------------------------- 0.0/547.3 kB ? eta -:--:--
   ---------------------------------------- 547.3/547.3 kB 6.1 MB/s eta 0:00:00
Downloading Cartopy-0.24.1-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ------ --------------------------------- 1.8/11.0 MB 9.1 MB/s eta 0:00:01
   -------------- ------------------------- 3.9/11.0 MB 9.4 MB/s eta 0:00:01
   --------------------- ------------------ 5.8/11.0 MB 9.3 MB/s eta 0:00:01
   ---------------------------- ----------- 7.9/11.0 MB 9.4 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.0 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 8.8 MB/s eta 0:00:00
Downloading pyproj-3.7.1-cp312-cp312-win_amd64.whl (6.3 MB)
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ----------- ---------------------------- 1.8/6.3 MB 9.1 MB/s eta 0:00:01
   ----------------------- ---------------- 3.7/6.3 MB 9.1 MB/s eta 0:00:01
   ------------------------------------ --- 5.8/6.3 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 6.3/6.3 MB 8.7 MB/s eta 0:00:00
Downloading shapely-2.1.1-cp312-cp312-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ------------------------------------ --- 1.6/1.7 MB 9.3 MB/s eta 0:00:01
   ---------------------------------------- 1.7/1.7 MB 7.1 MB/s eta 0:00:00
Downloading pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
Installing collected packages: shapely, pyshp, pyproj, cartopy, geoviews
Successfully installed cartopy-0.24.1 geoviews-1.14.0 pyproj-3.7.1 pyshp-2.3.1 shapely-2.1.1
Note: you may need to restart the kernel to use updated packages.

In [11]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests

# Import API key
from api_keys import geoapify_key

In [5]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,puerto baquerizo moreno,-0.9000,-89.6000,27.55,69,40,7.20,EC,1749490378
1,1,sitka,57.0531,-135.3300,8.94,81,100,1.54,US,1749490380
2,2,waitangi,-43.9535,-176.5597,10.70,65,96,13.71,NZ,1749490381
3,3,ushuaia,-54.8000,-68.3000,8.81,71,0,1.03,AR,1749490382
4,4,haiku-pauwela,20.9219,-156.3051,24.57,78,22,6.26,US,1749490383

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [13]:
%%capture --no-display

# Configure the map plot
map_plot = city_data_df.hvplot.points(
    "Lng",
    "Lat",
    geo = True,
    size = "Humidity",
    scale = 1,
    color = "City",
    alpha = 0.5,
    tiles = "OSM",
    frame_width = 700,
    frame_height = 500
)

# Display the map
map_plot

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City,Humidity)

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [15]:
# Narrow down cities that fit criteria and drop any results with null values
narrowed_city_df = city_data_df.loc[
    (city_data_df["Max Temp"] < 27) & (city_data_df["Max Temp"] > 21) \
    & (city_data_df["Wind Speed"] < 4.5) \
    & (city_data_df["Cloudiness"] == 0)
]

# Drop any rows with null values
narrowed_city_df = narrowed_city_df.dropna()

# Display sample data
narrowed_city_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
69,69,pratt,37.6439,-98.7376,26.12,29,0,4.12,US,1749490460
112,112,cranbrook,49.4999,-115.7688,25.91,29,0,2.57,CA,1749490511
118,118,hauterive,46.0901,3.4459,22.97,47,0,2.16,FR,1749490518
165,165,tura,25.5198,90.2201,26.09,70,0,1.76,IN,1749490573
251,251,as salt,32.0392,35.7272,26.60,45,0,2.08,JO,1749490674
295,295,beira,-19.8436,34.8389,25.05,73,0,4.12,MZ,1749490726
316,316,carnarvon,-24.8667,113.6333,21.35,49,0,3.10,AU,1749490751
349,349,rexburg,43.8260,-111.7897,23.23,38,0,2.06,US,1749490790
357,357,tezu,27.9167,96.1667,24.27,87,0,2.14,IN,1749490801
383,383,arcachon,44.5875,-1.0519,26.03,47,0,3.60,FR,1749490834
398,398,ambovombe,-25.1667,46.0833,22.39,66,0,2.65,MG,1749490851
408,408,vernal,40.4555,-109.5287,25.84,22,0,3.09,US,1749490864
442,442,archangelos,36.2149,28.1149,24.06,54,0,1.32,GR,1749490903
473,473,saint-francois,46.4154,3.9054,22.69,47,0,1.54,FR,1749490937
522,522,cabras,39.9300,8.5314,24.47,54,0,3.86,IT,1749490993
524,524,elmali,36.7358,29.9177,21.32,50,0,1.88,TR,1749490996
530,530,chapaev,50.2000,51.1667,22.10,29,0,4.12,KZ,1749491002

### Step 3: Create a new DataFrame called `hotel_df`.

In [17]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity
hotel_df = narrowed_city_df[["City", "Country", "Lat", "Lng", "Humidity"]].copy()

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df

               City Country      Lat       Lng  Humidity Hotel Name
69            pratt      US  37.6439  -98.7376        29
112       cranbrook      CA  49.4999 -115.7688        29
118       hauterive      FR  46.0901    3.4459        47
165            tura      IN  25.5198   90.2201        70
251         as salt      JO  32.0392   35.7272        45
295           beira      MZ -19.8436   34.8389        73
316       carnarvon      AU -24.8667  113.6333        49
349         rexburg      US  43.8260 -111.7897        38
357            tezu      IN  27.9167   96.1667        87
383        arcachon      FR  44.5875   -1.0519        47
398       ambovombe      MG -25.1667   46.0833        66
408          vernal      US  40.4555 -109.5287        22
442     archangelos      GR  36.2149   28.1149        54
473  saint-francois      FR  46.4154    3.9054        47
522          cabras      IT  39.9300    8.5314        54
524          elmali      TR  36.7358   29.9177        50
530         chapaev      KZ  50.2000   51.1667        29

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [19]:
# Set parameters to search for a hotel
radius = 1000
params = {
    "categories":"accommodation.hotel",
    "apiKey": geoapify_key,
    "limit":20
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():
    # get latitude, longitude from the DataFrame
    latitude = row["Lat"]
    longitude = row["Lng"]

    # Add the current city's latitude and longitude to the params dictionary
    params["filter"] = f"circle:{longitude},{latitude},{radius}"
    params["bias"] = f"proximity:{longitude},{latitude}"

    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"

    # Make and API request using the params dictionary
    name_address = requests.get(base_url, params=params)

    # Convert the API response to JSON format
    name_address = name_address.json()

    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["features"][0]["properties"]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"

    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df

Starting hotel search
pratt - nearest hotel: No hotel found
cranbrook - nearest hotel: No hotel found
hauterive - nearest hotel: No hotel found
tura - nearest hotel: No hotel found
as salt - nearest hotel: No hotel found
beira - nearest hotel: Hotel Savoy
carnarvon - nearest hotel: No hotel found
rexburg - nearest hotel: No hotel found
tezu - nearest hotel: No hotel found
arcachon - nearest hotel: No hotel found
ambovombe - nearest hotel: No hotel found
vernal - nearest hotel: Landmark Inn and Suites
archangelos - nearest hotel: Semina
saint-francois - nearest hotel: No hotel found
cabras - nearest hotel: Villa Canu
elmali - nearest hotel: Tu-Ba Hotel
chapaev - nearest hotel: No hotel found

,City,Country,Lat,Lng,Humidity,Hotel Name
69,pratt,US,37.6439,-98.7376,29,No hotel found
112,cranbrook,CA,49.4999,-115.7688,29,No hotel found
118,hauterive,FR,46.0901,3.4459,47,No hotel found
165,tura,IN,25.5198,90.2201,70,No hotel found
251,as salt,JO,32.0392,35.7272,45,No hotel found
295,beira,MZ,-19.8436,34.8389,73,Hotel Savoy
316,carnarvon,AU,-24.8667,113.6333,49,No hotel found
349,rexburg,US,43.8260,-111.7897,38,No hotel found
357,tezu,IN,27.9167,96.1667,87,No hotel found
383,arcachon,FR,44.5875,-1.0519,47,No hotel found
398,ambovombe,MG,-25.1667,46.0833,66,No hotel found
408,vernal,US,40.4555,-109.5287,22,Landmark Inn and Suites
442,archangelos,GR,36.2149,28.1149,54,Semina
473,saint-francois,FR,46.4154,3.9054,47,No hotel found
522,cabras,IT,39.9300,8.5314,54,Villa Canu
524,elmali,TR,36.7358,29.9177,50,Tu-Ba Hotel
530,chapaev,KZ,50.2000,51.1667,29,No hotel found

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [21]:
%%capture --no-display

# Configure the map plot
map_plot = hotel_df.hvplot.points(
    "Lng",
    "Lat",
    geo = True,
    size = "Humidity",
    scale = 1,
    color = "City",
    alpha = 0.5,
    tiles = "OSM",
    frame_width = 700,
    frame_height = 500,
    hover_cols = ["Hotel Name", "Country"]
)

# Display the map
map_plot

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City,Humidity,Hotel Name,Country)